### ISSUE TITLE
cant start wordpress locally

### ISSUE THREAD

**Issue by colinschwebke** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#64]
i am getting this error:

2016-06-14 22:54:23 Running command: "['C:\\Python34\\pythonw.exe', 'C:\\Program Files\\Google\\google_appengine\\dev_appserver.py', '--skip_sdk_update_check=yes', '--port=8080', '--admin_port=8000', 'C:\\Users\\Colin Schwebke\\Documents\\Websites\\vahle-taxi']"
Traceback (most recent call last):
  File "C:\Program Files\Google\google_appengine\dev_appserver.py", line 84, in <module>
    _run_file(__file__, globals())
  File "C:\Program Files\Google\google_appengine\dev_appserver.py", line 80, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
NameError: name 'execfile' is not defined
2016-06-14 22:54:24 (Process exited with code 1)

Please tell me what i am doing wrong.

Regards
Colin

**Comment by tmatsuo** [comment]
The dev_appserver needs to be run by Python 2.7.x. Is it possible to install Python2.7, or probably you may want to use my script at:
https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/wordpress

**Comment by colinschwebke** [comment]
Hello Takashi,

I installed Python 2.7 and 3.4. Google App engine seems to run Python 3.4?
So what shall i do?

Regards
Colin

Von:  Takashi Matsuo <notifications@github.com>
Antworten an:  GoogleCloudPlatform/appengine-php-wordpress-starter-project
<reply+01303b20351f9afd7da0f2ef76eaab798f3b298805ce70e292cf00000001137838039
2a169ce098db748@reply.github.com>
Datum:  Dienstag, 14. Juni 2016 um 23:24
An:  GoogleCloudPlatform/appengine-php-wordpress-starter-project
<appengine-php-wordpress-starter-project@noreply.github.com>
Cc:  Colin Schwebke <colin.schwebke@googlemail.com>, Author
<author@noreply.github.com>
Betreff:  Re: [GoogleCloudPlatform/appengine-php-wordpress-starter-project]
cant start wordpress locally (#64)


The dev_appserver needs to be run by Python 2.7.x. Is it possible to install
Python2.7, or probably you may want to use my script at:
https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengin
e/wordpress


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/appengine-php-wordpress-starter-proj
ect/issues/64#issuecomment-226020781> , or mute the thread
<https://github.com/notifications/unsubscribe/ATA7IFUmkg4msfWygbQWjZMXeVXDTD
xWks5qLxwDgaJpZM4I1wSP> .

**Comment by kkimball** [comment]
The App Engine SDK uses Python 2.7.  You'll want to make sure the proper python version is in your system's PATH. You can do this by running `python --version`.

The issue you're having is with the underlying SDK setup and not the WordPress starter project.  I recommend checking out the [quick start documentation](https://cloud.google.com/appengine/docs/python/quickstart) and getting the helloworld python app up and running.  Once that's working you shouldn't have this issue with this project.

Also, as previously mentioned by tmatsuo, you should consider using the code at https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/wordpress instead of this project.

Good luck!

**Comment by jgacuca567** [comment]
@colinschwebke are you still having problems setting up locally?
